sudo: required
dist: trusty
branches:
  only:
    - master
    - release
    - develop
language: scala
scala:
  - 2.11.12
  - 2.12.6
env:
  - JDK=openjdk8
  - JDK=oraclejdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lp-solve liblpsolve55-dev unzip
  - sudo wget https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.5/lp_solve_5.5.2.5_java.zip
  - unzip lp_solve_5.5.2.5_java.zip
  - sudo cp lp_solve_5.5_java/lib/ux64/liblpsolve55j.so /usr/lib/lp_solve
  - export LB_LIBRARY_PATH=$LB_LIBRARY_PATH:/usr/lib/lp_solve
before_script:
  - jdk_switcher use $JDK
script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "testOnly optimus.optimization.LPSolve* optimus.optimization.OJ*"
  - git diff --exit-code