name: Optimus CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run tests
        run: sbt "++${TRAVIS_SCALA_VERSION}" "core/test" "solver-oj/testOnly optimus.optimization.OJ*"